SELECT 
    e.EMPLOYEE_ID AS ID_FUNCIONARIO,
    e.FIRST_NAME || ' ' || e.LAST_NAME AS NOME_FUNCIONARIO,
    e.SALARY AS SALARIO,
    d.DEPARTMENT_NAME AS NOME_DEPARTAMENTO,
    l.CITY AS CIDADE,
    l.STATE_PROVINCE AS ESTADO,
    c.COUNTRY_NAME AS PAIS,
    r.REGION_NAME AS REGIAO
FROM 
    HR.EMPLOYEES e
LEFT JOIN 
    HR.DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN 
    HR.LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID
LEFT JOIN 
    HR.COUNTRIES c ON l.COUNTRY_ID = c.COUNTRY_ID
LEFT JOIN 
    HR.REGIONS r ON c.REGION_ID = r.REGION_ID
WHERE 
    r.REGION_NAME IS NOT NULL;