SELECT 
    e.EMPLOYEE_ID AS ID_FUNCIONARIO,
    e.FIRST_NAME || ' ' || e.LAST_NAME AS NOME_FUNCIONARIO,
    e.SALARY AS SALARIO,
    d.DEPARTMENT_NAME AS NOME_DEPARTAMENTO,
    j.JOB_TITLE AS TITULO_CARGO
FROM 
    HR.EMPLOYEES e
LEFT JOIN 
    HR.DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN 
    HR.JOBS j ON e.JOB_ID = j.JOB_ID
WHERE 
    e.DEPARTMENT_ID IS NOT NULL;